### ISSUE TITLE
G1 curriculum debrief needs to be written up.

### ISSUE THREAD

**Issue by ronanyeah** [foundersandcoders/gaza-curriculum#9]
I have the notes. Will write up something similar to [this](https://github.com/foundersandcoders/master-reference/blob/master/curriculum-planning/minutes/london-initial-planning.md).

**Comment by eliascodes** [comment]
@ronanyeah any idea when I'll be able to look at this (even just a draft)? I figure it could be useful to have an idea of what G1 have said ahead of London's curriculum planning week on Tuesday.

**Comment by ronanyeah** [comment]
@eliascodes Apologies for the delay, I have been heavily 'decompressing'. Wrote them up today and will put them up soon. Cliff notes are 'more promises, more ES6, more vanilla node, more complex front end'.
